#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title: Scientific Computing & Data Analysis
author: Lin Deng
logo: fig/logo.png
copyright: "2022" 
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [ README.md, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]


#######################################################################################
# Execution settings
execute:
  execute_notebooks: "cache"
  # cache            : ""
  
#######################################################################################
# Parse and render settings
parse:
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
  myst_enable_extensions    :
   - colon_fence
   - dollarmath
   - linkify
   - substitution

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "fig/favicon.png"  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Post any questions to the <a href="https://www.askpbs.org/c/naturalistic-data/">Discourse Page</a>  # Will be displayed underneath the left navbar.
  extra_footer              : Created by <a href="https://github.com/linchrisdeng/">Lin Deng</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://linchrisdeng.github.io/SCNA/content/notebooks.html"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use jupyterbook-latex for pdf builds as default
# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/linchrisdeng/SCNA
  path_to_book              : ""
  branch                    : main  # Which branch of the repository should be used when creating links
  
#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx (added to those already used by JB).
    # - sphinx_inline_tabs
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
  

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

